### ISSUE TITLE
Editorial: Re-write "motivation" section to de-emphasize centralization argument, emphasize scaling

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#132]
**Which part needs editing?**
01_introduction.asciidoc
section: === Motivation for the Lightning Network

**What editing does this need?**
Not sure if centralization should be the first / main argument when discussing why increasing blockspace / decreasing blocktime does not work. 

I think it is an important argument but it comes with ideology - as bitcoin - and thus it seems to open up space for discussions. There are actually simple technical arguments that demonstrate that even from a pure technical / non ideological point of view it does not make sense. Since I would love to stop the discussion and give people better (?) / technical arguments. I am not strongly opinionated on this feedback though but thought I mention it. 

**How does it currently read?**
However, simply increasing block size does not solve the problem because it has the undesirable effect of centralizing the network. Because blockchains are gossip protocols, each node is required to know and validate every single transaction that occurs on the network

**How should it read?**
We could argue how much data was to process and how expensive it would become to run a bitcoin node (even without mining) how much internet traffic this would need and so on. The plain argument of a broadcast replicated system in which every participant needs to process everything is something that you already give so we could focus on that

**Comment by ImranLorgat** [comment]
Hi Rene

This paragraph was my contribution and my intention was to keep it technical i.e. that achieving scaling through increasing block size has many drawbacks. I mentioned below the storage/processing requirements for each node, as well as the calcs by Poon and Dryja. From what I understand there are also issues in validation and block propagation around the network in the space of 10 minutes. 

It's a pity that a technical parameter like block size has become such an ideological point. I was thinking my following comment was ideological: _"because it has the undesirable effect of centralizing the network"_. I mean, this is only a problem if you think centralization of money and the financial system is bad.

Potentially we could also bring up Hal Finney's comments on second layer. He understood the need for a second layer all the way back in 2010. 

https://www.reddit.com/r/Bitcoin/comments/7pgrhb/hal_finney_understood_the_need_of_2nd_layer/

**Comment by ImranLorgat** [comment]
P.S. Core Developer Luke Dashjr has also previously argued for smaller block sizes. He has a strong technical argument for taking as many transactions off-chain as possible, even without decreasing block size.

https://medium.com/chainrift-research/to-reduce-or-not-to-reduce-the-block-size-ed42795f3891
