### ISSUE TITLE
Development environment standardization

### ISSUE THREAD

**Issue by aantonop** [lnbook/lnbook#158]
In order to make it easier for users to follow the examples, we have made two decisions to standardize the development environment. These decisions will be implemented as part of Chapter 4

1) We will be using a Docker container to build a consistent environment in which all the examples can be run and tested. The Dockerfile will be shared on this repository and instructions to run it will be included in the text

2) We will be using Bitcoin in REGTEST mode, and providing instructions on how to deploy and use regtest and LN on top of it. This will alleviate the need to bootstrap a node and help developers understand the power of using regtest in a dev environment. 

Maybe one day we can "backport" both of these ideas into Mastering Bitcoin, if we execute successfully here...

Topics for discussion:

* Is Docker the right choice?

 I think it will help users of Windows, Mac and various other systems load a standardized dev environment. Though many developers in our space run some version of Linux, there are also many readers who do not and would find it difficult to replicate our examples. We can't offer tools and examples for every OS, so we have to pick one

* If Docker, what OS and image

I think we should standardize on Ubuntu 18.04 LTS, because it is the most supported OS across all the open source projects. As an LTS version (Long Term Support), it will be supported until April 2023. By then we will be in a second edition and can move to the next LTS version. The downside is that an Ubuntu 18.04 image is much "heavier" than say alpine, but the purpose of this container is to be very very standard and have the most well known tools, so it is worth paying the price in disk space for Ubuntu. 

* How much of the dev environment should be packaged in the Docker image?

I think at least the basic dev tools and pre-requisite libraries for the various tools we will install (eg. all the things you apt install before bitcoin, Go support for lnd, etc). Do we also pre-install bitcoind latest from PPA? Or do we include that in the examples so that people can learn how to do it on their own? Mastering Bitcoin already covers all that in chapter 3 and I don't want to repeat too much. 

* Separate repository?

Should we make a separate repository for the Docker image, scripts and examples, so that we can clone it and make it part of the Docker container, without having to pull in the book itself? I think so....

Please add your thoughts and suggestions!

**Comment by bolatovumar** [comment]
- Is Docker the right choice?
Definitely. I work on Windows and Mac and find projects that use Docker (like BTCPay Server for example) much easier to get started with then with projects where you have to set-up your environment manually.

-If Docker, what OS and image
Agree with the Ubuntu 18.04 LTS choice.

-How much of the dev environment should be packaged in the Docker image?
Including everything needed to get started is probably the easiest for a future reader. However, it would be nice to mention the advantages of compiling bitcoind from source yourself and point to a guide for it if we don't want to include the guide in this book.

- Separate repository?
Yes, agreed.

**Comment by fguisso** [comment]
Docker the right choice?
Agree. Easier, fast and multiplataform.

what OS and image?
I every use alpine, is simple and light image good to create clean containers. LND has some good examples with docker and docker-compose to generate a awesome LN cluster network.

I think is better than have different dockerfiles and docker-compose files too, in #164 using one dockerfile to install all the books needs seems to much for me. Thinking in a guy that want just to execute a lesson, why he needs to download all the things?

I like to think in another repo dedicate to dockerfiles and others needs, a few mouths ago I port the [LND](https://github.com/lightningnetwork/lnd/tree/master/docker) docker-compose to [DCRLND](https://github.com/decred/dcrlnd/tree/master/docker) and I learned a lot because some network peculiarities.
If you agree, I can take care of dockerfiles, discuss with all and create the dockerfiles based on the lesson.

btw, I know that the book will cover a lot os tools, but what is the main tool that will be used? e.g. most explanations will be done with `bitcoind` and `lnd`

**Comment by aantonop** [comment]
I've pushed another set of changes in #164 that:
- Split into separate Dockerfile folders for each of the components, allowing us to build more complex setups in a modular way. Each is tagged as the "base" image. 
- Still have a single "devenv" Dockerfile that contains all the components in one place
- Provide a docker-compose file, which for now just builds all the Docker images

Next I will work on making:

- A Dockerfile that sets up bitcoind in regtest mode, ready to serve up blocks and transactions to LN nodes
- Dockerfiles that build from the base images to configure each of the LN nodes with a basic configuration file. 
- A docker-compose that connects a set of LN nodes around a regtest bitcoind and sets up channels
