### ISSUE TITLE
Editorial: Reduce expectations, replacing "very low fees" with "low fees", etc.

### ISSUE THREAD

**Issue by 8go** [lnbook/lnbook#171]
**Which part needs editing?**
Chapter 1, most likely all others as well.

**What editing does this need?**
Simplify

**How does it currently read?**
very cheap, very low cost, ... very expensive

Users of the Lightning Network can route payments to each other for very low cost and in real time.
... so he uses the Lightning Network to accept bitcoin payments almost instantaneously and for very low fees.
Remittance companies and banks charge very high fees

**How should it read?**
Low? Very low? This is all relative. What is a "very low" fee or a "very low cost" payment? It is different for different readers. We should not create expectations that are too high. Remember when Bitcoiners spoke about "very low fees" on Bitcoin and micro-payments on bitcoin? In just a handful of years the perception has changed. The expectations should be as realistic as possible and if in doubt I would rather suggest to under-hype than to over-hype a technology. Hence, I suggest to simply replace the "very low" and "very cheap" etc phrasing with simply "low", i.e. remove the word "very".

Users of the Lightning Network can route payments to each other for low cost and in real time.
... so he uses the Lightning Network to accept bitcoin payments almost instantaneously and for low fees.
Remittance companies and banks charge high fees ...

If people agree with reducing the suggested reduction in expectations, I'd be happy to put all the changes into a single PR. Just let me know.

**Comment by Roasbeef** [comment]
Agreed that it's all relative, and we want to ensure we set expectations and not overpromise as the routing fee market will evolve further once routing node operators become more educated and sophisticated themselves. 

I like the suggested re-wording, and each time we mention the fees we should always point out that the fees will _likely_ (and currently) are lower than on-chain fees, as these users aren't bidding for scarce block space (fixed supply). Instead this is an off-chain market where the fees go to those that routed the payment, rather than the one that mined the block. Additionally, one big difference between on and off-chain fees is that on-chain you pay per byte, while off-chain you pay on a percentage basis. As a result, certain payment types may always stay on-chain (billion dollar values, etc) as the fee for them is effectively constant, all else held equal. While off-chain the larger the amount, the higher fee you pay.

**Comment by 8go** [comment]
It was also in Chapter 2. 

I already started to put in PRs (some I think have already been pulled, some still pending) where I removed terms such as "very expensive", "extremely slow", etc. with more factual description such as "expensive", "slower than" as appropriate. 

Let's stay as factual as we can be.

**Comment by 8go** [comment]
put in PR #272 for ch01
ch02 seems OK already
ch03 seems OK too

**Comment by 8go** [comment]
ch01 ch02 and ch03 are OK now. Closing issue.
