### ISSUE TITLE
Editorial: Cover Art is Kinda Scary

### ISSUE THREAD

**Issue by CypherPoet** [lnbook/lnbook#331]
I'm not one to judge books by their cover, and I say this with utmost respect for the commissioned artist, but... the [current artwork](https://github.com/lnbook/lnbook/blob/develop/images/Mastering%20the%20Lightning%20Network%20Cover.png) is going to scare the shit out of a lot of people.

Given that we're still pretty early in the process, I'm wondering if there's a way to ask for a change. I don't have any specific ideas -- I'd rather respect the liberties of the aforementioned artist (and [O'Reilly's terrific "animals" initiative](https://www.oreilly.com/content/a-short-history-of-the-oreilly-animals/)) -- but the last thing I'd want is for such an amazing resource to be created, only to have sales and readership suffer because of an aesthetic oversight. 

I'm not entirely sure how this would get handled -- I'm guessing O'Reilly is calling such shots -- but I still felt compelled to raise the issue here if it helps alert the right people ✌️ .

**Comment by aantonop** [comment]
We have very little control over the cover art. 

We recommended "wood ants", as ants are a social species that best represent the decentralized nature of Bitcoin and Lightning and the wood ants make networks of colonies in a forest. 

No one is buying this book because they saw the cover, nor are they *not* buying this book because of the cover. This isn't an impulse buy. It is the only book of its kind and it will set the standard, just like Mastering Bitcoin and Mastering Ethereum did. 

For all the above reasons, we cannot and will not change the cover art.
