### ISSUE TITLE
Topic suggestion: LN Protocol Layer Diagram

### ISSUE THREAD

**Issue by Roasbeef** [lnbook/lnbook#342]
During our past meeting, the topic of a layered protocol diagram came up. This diagram could live somewhere in section 3 in order to lay the ground for the deeper exploration of each layer in the later chapters. It'll also help the reader to crystalize a "top down" model of LN in their head, as for the most part that's the progression we plan on following. 

During the later portion of the call I jotted down a possible outline (the layers not the diagram), which would be something like:

* Application layer (lapps) 
* Wallets
* Presentation/session -- BOLT 11, LN URL, LSAT, etc 
    * communicates how to pay, and the details 
* Gossip layer / graph 
    * Channel ann, channel upd, node ann 
* Path finding 
    * Algo choice, payload construction, optimization and heuristics
* Routing/forwarding
    * Multi-hop, forwarding, forwarding handling  
* Link layer updates 
    * State machine -- add settle cancel, 1.5 RTT, htlc format 
    * Conditional chained e2e payment (abstraction over HTLCs) 
* Channel construction format 
    * LN, eltoo, el tres 
* Funding output anchoring 
* P2P layer 
* Framing (wire messages) 
* Encrypted transport (noise)

**Comment by Roasbeef** [comment]
For reference, here's something that cdecker has used in the past in his presentations: https://blockstream.com/img/blog/2018-04-30/lightning-layers.png

**Comment by ysangkok** [comment]
Wouldn't it be better to have multiple stacks, instead of just a single OSI like hierarchy? For example, LN nodes can have proprietary centralized gossip/pathfinding channels, and it would even be possible to have an LN node that does not gossip (probably already exists with some flags, at least?).

An upper layer could even base upon those stacks like in [this diagram of the Linux graphics stack](https://upload.wikimedia.org/wikipedia/commons/9/99/Linux_kernel_and_OpenGL_video_games.svg).

**Comment by Roasbeef** [comment]
Here's a shot at an instance inspired by something Rene showed me a few weeks ago (very rough, mostly want to capture the entity relations): 

![stack-diagram](https://user-images.githubusercontent.com/998190/112879240-bfe99480-907d-11eb-96f3-0dfad1fe8a3d.png)

**Comment by renepickhardt** [comment]
As discussed yesterday  I believe we should separate BOLT / protocol architecture from the implementation specific acitecture

I tried to make a next version that focuses a little bit more on the BOLTs. The Payment Layer has a few things that are not in the BOLTs and BOLT 03 / 05 are missing completely (so everything related to bitcoin) though technically it is part of some of the boxes

![lnbook-graphics (2)](https://user-images.githubusercontent.com/1926816/113031991-a0db2780-918f-11eb-91f3-60d6d40b36bd.png)

I am still not too happy with some of the boxes, naming, formatting etc. but I think we are getting there. Obviously we could also introduce some color coding and also arrows between the boxes. I tried to also have some sense in the vertical direction but that was much harder and I am breaking this which is why the horizontal ordering of the boxes in some layers could be reshuffled

**Comment by renepickhardt** [comment]
In particular I think the "routing" layer might be better to be called transport layer because in the context of lightning network this is actually where the payment (HTLCs) is being transported which is why I was considering to call the lower layer connection layer because it is more about the network connection.

**Comment by renepickhardt** [comment]
I have created and updated version based on some feedback and further thoughts

![lnbook-graphics (5)](https://user-images.githubusercontent.com/1926816/113750862-9549ac80-970b-11eb-9e7c-5b34e66694af.png)

and I also shared it on [Wikimedia commons](https://commons.wikimedia.org/wiki/File:Lightning_Network_Protocol_Suite.png)where future version can also be maintained by an open source developer community and where it can be used for the wikipedia article

**Comment by renepickhardt** [comment]
diagram is ready and merged
