### ISSUE TITLE
Fix needed [Typo, Grammar, Syntax, Terminology, Spelling, Fact, Code]

### ISSUE THREAD

**Issue by tomichec** [lnbook/lnbook#353]
**Describe the error**
In the description of onion routing appears a name David, however it is not explained who he is and neither appears in the diagrams. I suppose it's just another name for Bob.

**To Fix**
+ or change the name of David to Bob,
+ or explain who David is and what is his role.

**Additional context**
related to the routing.asciidoc chapter

**Comment by renepickhardt** [comment]
david is gloria (: and indeed it needs to be fixed

**Comment by motorina0** [comment]
- the text was fixed in PR https://github.com/lnbook/lnbook/pull/550 
- it includes replacing **he** with **she**
- David is still present in the header of some diagrams (although it has been replaced with Gloria in the box)
   - ![image](https://user-images.githubusercontent.com/2951406/100377326-b8f03e00-3019-11eb-86b2-8b4b6e688ff1.png)
- Ek D vs Ek G
   - ![image](https://user-images.githubusercontent.com/2951406/100445642-1d60db00-30b6-11eb-97d2-e8f3e12391b2.png)

**Comment by renepickhardt** [comment]
I think the diagrams have been exchanged anyway in the meantime. The mentioned PR needs rebase so I think the issue can be closed
