### ISSUE TITLE
Help Me Understand: What makes a channel "visible" on-chain upon closure?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#441]
**Which topic needs more explanation?**
The text mentions that LN channels are "invisible" but only before they are closed; at closure they become "visible" on-chain.

**What about the topic is not understood?**
From the on-chain point of view, LN opening is just a 2-of-2 multisig. We consider this "invisible", so far so good. But the channel closure is just a spending from a multisig. What about the closing transaction makes the existence of a channel visible to on-chain observers?

**What does this topic needs to be easier to understand?**
Clarify how a closing transaction can be distinguished on-chain from a regular spending from a multisignature address.

**Comment by aantonop** [comment]
We will need to address this in channel construction and operation, where we describe the specific scripts used in channels. It is premature to discuss in chapter 3, too deep. 

In short: Channel funding involves payment to a script address (2-of-2). A script address is opaque and only presents a hash of the script. It is not possible to distinguish a LN channel funding from a payment to any other type of script. But on channel closure, in order to spend from the 2-of-2, you need to present the *actual* script. That's how Pay-to-Script works: the script is presented for validation on spending, not on funding. That script is clearly an LN channel script. Once it is identified as a channel closing transaction, we now have confirmed the existence of the channel as well as it's starting and ending balances.

**Comment by s-tikhomirov** [comment]
> That script is clearly an LN channel script.

But this is still an heuristic, isn't it? Is it true that one could use the same script with a regular 2-of-2 multisig?

**Comment by renepickhardt** [comment]
I believe this is by now sufficiently covered in channel construction. feel free to reopen if I should be wrong on this.
