### ISSUE TITLE
Turkish Translation of the book

### ISSUE THREAD

**Issue by efecini** [lnbook/lnbook#668]
Although I am not an official translator, I am a software engineer who translated bitcoin whitepaper into Turkish on bitcoin.org (can be seen here : https://bitcoin.org/files/bitcoin-paper/bitcoin_tr.pdf). I consider myself as a bitcoiner and recently leaning on the lightning network and possible upper layers. Is there a way to translate the ln book into the Turkish and be the official translator? I don't know if it raises any legal issues about copyright or something like that because I really would to publish it in Turkey too and see it on the book stores. Thanks.

**Comment by giovannizotta** [comment]
Hi @efecini, thanks for your support. In the latest livestream (https://youtu.be/U0T49duRt74?t=2085), Andreas said that unfortunately it won't be possible to start the translation process until a year after publication due to copyright limitations. From what I have understood, it is possible to start working on the translation before the 1 year threshold, but it won't be possible to actually use your work until the one-year clock has expired.

**Comment by efecini** [comment]
Ok, but it seems like -considering the Creative Commons license- there is no limitation for me to start the translation work by forking the repo, right? In the end, I am not distributing the book commercially. Am I right?

**Comment by giovannizotta** [comment]
I think you're right. Just keep in mind that in the meanwhile the book might change its structure and you may be forced to adapt your work to it. In any case I would suggest to wait for the opinion of the authors on this matter

**Comment by efecini** [comment]
Fine. I am waiting for their comment. Then, I will close the issue. Thanks

**Comment by efecini** [comment]
Ok I guess I've waited long enough for a response from the authors. It looks like they don't care. Closed.
